### ISSUE TITLE
Is that compatible to version 1.4.1.20 ?

### ISSUE THREAD

**Issue by lotc** [YuriDLL/stacklands-recipes#5]
Just found this helpful recipe cheatsheet.
But it seems that the game has a newer version, does this sheet still cover all the recipes?

**Comment by YuriDLL** [comment]
I haven't updated data in over two years. If desired, you can update the card and recipes in the **data** directory.  But the game has changed a lot during this time and the site structure may not allow all changes to be reflected.

**Comment by lotc** [comment]
Okay, I'll dig it myself.
Thanks for reply.
